print("SJC23MCA032 : JACOB K M")
import numpy as np
arr_id=np.array([1,2,3,4])
print("\n ID  before insertion\n")
print(arr_id)
arr_id=np.insert(arr_id,4,6)
print("\n after")
print(arr_id)
arr_2d=np.array([[1,2,3],[4,5,6]])
print("Original 2 d array")
print(arr_2d)
arr_2d = np.insert(arr_2d,1,[7,8,9],0)
print("2d after insertiion")
print(arr_2d)